AWSTemplateFormatVersion: '2010-09-09'
Description: Create a DynamoDB table

Parameters:
  TableName:
    Type: String
    Description: "DynamoDB table Name"
    Default: "DefaultTableName"

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: City
          AttributeType: S
        - AttributeName: PersonName
          AttributeType: S
        - AttributeName: Age
          AttributeType: N
      KeySchema:
        - AttributeName: City
          KeyType: HASH
        - AttributeName: PersonName
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  TableNameOutput:
    Description: "DynamoDB table Name"
    Value: !Ref DynamoDBTableName
